config/routes.rb
Rails.application.routes.draw do
  get '/users', to: 'users#index', as: 'users'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:user_id/posts', to: 'posts#index', as: 'user_posts'
  get '/users/:user_id/posts/new', to: 'posts#new', as: 'new_post'
  post '/users/:user_id/posts/create', to: 'posts#create', as: 'create_post'
  get '/users/:user_id/posts/:id', to: 'posts#show', as: 'user_post'

  get '/users/:user_id/posts/:id/comments/new', to: 'comments#new', as: 'new_comment'
  post '/users/:user_id/posts/:id/comments/create', to: 'comments#create', as: 'create_comments'

  get '/users/:user_id/posts/:id/likes/new', to: 'likes#new', as: 'new_like'
  post '/users/:user_id/posts/:id/likes', to: 'likes#create', as: 'create_likes'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :comments_counter
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :likes_counter
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', counter_cache: :posts_counter
  has_many :likes
  has_many :comments

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def five_recent_comments
    comments.sort_by(&:created_at).reverse.take(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: :author_id
  has_many :likes
  has_many :comments

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: %i[new create]

  def set_post
    @post = Post.find(params[:id])
  end

  def new
    @new_comment_model = Comment.new
  end

  def create
    @new_comment_model = Comment.new(allowed_comment_params)
    @new_comment_model.user_id = current_user.id
    @new_comment_model.post_id = @post.id

    if @new_comment_model.save
      redirect_to user_post_path(current_user, @post)
    else
      render :new
    end
  end

  def allowed_comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @like = Like.new
    @post = Post.find(params[:id])
    @like.post_id = @post.id
    @like.user_id = current_user.id

    if @like.save
      redirect_to user_post_path(current_user, @post)
    else
      redirect_to user_posts_path(current_user)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET  /users/:user_id/posts
  # Fetching the all posts of the user with id = :user_id
  # def index
  #   @user = User.includes().find(params[:user_id])
  #   @posts = @user.posts
  # end

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end
  

  # GET  /users/:user_id/posts/:id
  # Fetching the details post with post id = :id
  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def new
    @user = User.find(params[:user_id])
    @new_post_model = @user.posts.new
  end

  def create
    @user = User.find(params[:user_id])
    @new_post_model = @user.posts.new(allowed_post_params)
    @new_post_model.comments_counter = 0
    @new_post_model.likes_counter = 0

    if @new_post_model.save
      redirect_to user_post_url(@user, @new_post_model)
    else
      render :new
    end
  end

  private

  def allowed_post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # HTTP METHOD: GET URL pattern: /users
  # Shows or fetches all users with image & User name + Number of posts : view 1
  def index
    @users = User.all
  end

  # HTTP METHOD: GET URL pattern: /users/:id
  # Shows or fetchers the user where :id is the ID of a user.
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>Add New Comment:</h1>
<%= form_with(model: @new_comment_model, url: create_comments_path) do |form| %>
  <div class="fpost">

    <div class="ftext">
      <%= form.label :text %> 
      <%= form.text_area :text %>
    </div>

    <div>
      <%= form.submit%>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/new.html.erb
<%= form_with(model: @like, url: create_likes_path) do |form| %>
    <div>
      <%= form.submit 'Submit Like'%>
    </div>
<% end %>

app/views/posts/_user_posts_all.html.erb
  <article class="uposts">
   <% posts.each do |post|%>
     <div class="detail full-width">
      <h3><%= link_to "Post ", user_post_url(@user.id, post.id) %> # <%= post.id %></h3>
      <h3><%= post.text %></h3>
      <p>Comments: <%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter || 0 %>
     </div>
     <div class="detail full-width d-margin">
      <% post.five_recent_comments.each do |comment| %>
      <p class="comments"><b><%= @user.name %>:</b> <%= comment.text %></p>
      <% end %>
     </div>
   <% end %>
  </article>

app/views/posts/index.html.erb
<div>
  <%= render partial: 'users/user_profile', locals: {user: @user}%>
</div>
<%= link_to new_post_url() do %>
  <button class="np-btn">Add A New Post</button>
<% end %>
<div class="posts">
 <%= render partial: 'user_posts_all', locals: {posts: @posts}%>
</div>
<div class="posts-details">
    <button type="button" >pagination</button>
</div>

app/views/posts/new.html.erb
<h1>Add New Post:</h1>
<%= form_with(model: @new_post_model, url: create_post_path(user_id: @user.id)) do |form| %>
  <div class="fpost">
    <div class="flabel">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="ftext">
      <%= form.label :text %> 
      <%= form.text_area :text %>
    </div>

    <div>
      <%= form.submit%>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="detail full-width d-margin">
    <div class="post-head">
      <h3>Post  #<%= @post.id %> by <%= @user.name %></h3>
      <span>Comments: <%= @post.comments_counter || 0 %> Likes:<%= @post.likes_counter || 0 %></span>
    </div>
    <p class="comments"><%= @post.text%></p>
</div>

<div class="detail full-width like-comment">
  <%= link_to new_comment_path(@post.id) do %>
    <button>Add New Comment</button>
  <% end %>

  <%= link_to new_like_path() do %>
    <button>Like</button>
  <% end %>
</div>

<div class="detail full-width">
      <% @post.comments.each do |comment| %>
      <p class="comments"><b><%= @user.name %>:</b> <%= comment.text %></p>
      <% end %>
</div>

app/views/users/_user_posts.html.erb
  <article class="uposts">
   <% user.three_recent_posts.each do |post|%>
     <div class="detail full-width">
      <h3>Post # <%= post.id %></h3>
      <h3><%= post.text %></h3>
      <p>Comments: <%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter || 0 %>
    </div>
   <% end %>
  </article>

app/views/users/_user_profile.html.erb
<%= link_to user_url(user.id) do %>
  <article class="profile">
    <div class="photo"><img src="<%= user.photo %>" alt="User photo"></div>
    <div class="detail">
      <h2><%= user.name %></h2>
      <p>Number of posts: <%= user.posts_counter %></p>
    </div>
  </article>
<% end %>

app/views/users/index.html.erb
<section>
 <% @users.each do |u| %>
  <%= render partial: 'user_profile', locals: {user: u}%>
 <% end %>
</section>

app/views/users/show.html.erb
<section class="user-container">
<div>
  <%= render partial: 'user_profile', locals: {user: @user}%>
</div>
<div class="bio">
<h3>Bio</h3>
<p><%= @user.bio%></p>
</div>
<div class="posts">
 <%= render partial: 'user_posts', locals: {user: @user}%>
</div>
<div class="posts-details">
 <%= link_to user_posts_path(@user.id) do %>
    <button type="button" >See all posts</button>
 <% end %>
</div>

</section>